apiVersion: apps/v1
kind: Deployment
metadata:
  environment: '${ parameters.environment }'  
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      id: app
  template:
    metadata:
      labels:
        id: app
    spec:
      containers:
      - image: XXX # needs to be overridden by environments
        name: nginx