apiVersion: v1
kind: Service
metadata:
  environment: '${ parameters.environment }'
  labels:
    app: service
  name: service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    id: app
  type: NodePort