apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapp
    environment: prod
  name: simpleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - image: jwilliams12/simpleapp
          imagePullPolicy: Always
          name: simpleapp
          ports:
            - containerPort: 80


